import { sidebar } from "vuepress-theme-hope";

export const zhSidebar = sidebar({
  "/": [
    "",
    {
      text: "如何使用",
      icon: "creative",
      prefix: "demo/",
      link: "demo/",
      children: "structure",
    },
    {
      text: "代码笔记",
      icon: "note",
      prefix: "posts/",
      children: [
        {
          text: "跨平台开发",
          icon: "relation",
          prefix: "cross-platform/",
          link: "cross-platform/",
        },
        {
          text: "前端开发",
          icon: "code",
          prefix: "Web/",
          link: "Web/",
        },
      ],
    },
    {
      text: "技术文章",
      icon: "stack",
      prefix: "technology/",
      children: [
        {
          text: "AI",
          icon: "hk-ai",
          prefix: "AI/",
          link: "AI/",
        },
        {
          text: "Java",
          icon: "java",
          prefix: "Java/",
          link: "Java/",
        },
        {
          text: "Golang",
          icon: "hk-golang",
          prefix: "Golang/",
          link: "Golang/",
        },
        {
          text: "Linux",
          icon: "linux",
          prefix: "Linux/",
          link: "Linux/",
        },
        {
          text: "Python",
          icon: "python",
          prefix: "Python/",
          link: "Python/",
        },
        {
          text: "Rust",
          icon: "hk-rust",
          prefix: "Rust/",
          link: "Rust/",
        },
        {
          text: "Web",
          icon: "code",
          prefix: "Web/",
          link: "Web/",
        },
      ],
    },
    {
      text: "金融知识",
      icon: "hk-finance",
      prefix: "finance/",
      link: "finance/",
      children: "structure",
    },
    {
      text: "软件/工具教程",
      icon: "software",
      prefix: "tutorial/",
      link: "tutorial/",
    },
    {
      text: "博客相关",
      icon: "blog",
      prefix: "blog/",
      link: "blog/",
    },
    {
      text: "站点收藏",
      icon: "sitemap",
      prefix: "site/",
      link: "site/",
      children: "structure",
    },
    {
      text: "随笔",
      icon: "flower",
      prefix: "private/",
      children: "structure",
    },
    {
      text: "关于",
      icon: "info",
      prefix: "about/",
      link: "about",
    },
  ],
  "/posts/cross-platform/Flutter/": "structure",
  "/posts/cross-platform/ReactNative/": "structure",
  "/posts/Web/": "structure",
  "/technology/AI/": "structure",
  "/technology/Java/": "structure",
  "/technology/Golang/": "structure",
  "/technology/Linux/": "structure",
  "/technology/Python/": "structure",
  "/technology/Rust/": "structure",
  "/technology/Web/": "structure",
  "/finance/": "structure",
  "/site/": "structure",
  "/blog/": "structure",
  "/tutorial/": "structure",
});
