# theme: jekyll-theme-cayman

# Site settings
title: 吾' Blog
SEOTitle: 吾蜀黍的博客 | W' Blog
header-img: img/home-bg.png
email: ipenfive@163.com
description: "吾蜀黍，Web & Front-end Engineer | 吾蜀黍的个人博客"
keyword: "wuxiansen, wushushu, W' Blog, 博客，Web, Css, Javascript"
url: "https://wuxiansen.com/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'


# avatar and Favicon
# avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: favicon.ico


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Web Developer"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# SNS settings
RSS: false
weibo_username:     false
zhihu_username:     false
github_username:    wuxiansen


# Build settings
paginate: 10
plugins: [jekyll-paginate]
# gems: [jekyll-paginate]


# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: a84c2a57837302767371                            #生成的clientID
  clientSecret: 847046720bec629fbd3580d8f3cc617ab9d3a27a    #生成的clientSecret
  repo: wuxiansen.github.io    #仓库名称
  owner: wuxiansen    #github用户名
  admin: wuxiansen
  # distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Friends
friends: [
  {
    title: "W' github",
    href: "https://wuxiansen.github.io/"
  },
  {
    title: "chenshuyao's blog",
    href: "https://chenshuyao.cn/"
  }
]
